//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManufactureFemExam.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.Spec = new HashSet<Spec>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public string Insurance { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public bool IsCustomer { get; set; }
        public bool IsManufacturer { get; set; }
    
        

        public string CompanyType
        {
            get
            {
                return IsCustomer == true ? "Клиент" : "Производитель";
            }
        }

        public virtual ICollection<Spec> Spec { get; set; }
    }
}
