//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManufactureFemExam.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderProduct = new HashSet<OrderProduct>();
        }
    
        public int id { get; set; }
        public int Number { get; set; }
        public System.DateTime date { get; set; }
        public decimal TotalPrice { get; set; }
        public bool IsOrder {  get; set; }

        public string OrderType
        {
            get
            {
                return IsOrder == true ? "В работе" : "Завершён";
            }
        }

        public virtual ICollection<OrderProduct> OrderProduct { get; set; }
    }
}
