//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManufactureFemExam.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecMaterial
    {
        public int id { get; set; }
        public int SpecId { get; set; }
        public int MaterialId { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual Spec Spec { get; set; }
    }
}
