//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManufactureFemExam.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spec
    {
        public Spec()
        {
            this.SpecMaterial = new HashSet<SpecMaterial>();
        }
    
        public int id { get; set; }
        public int ProductId { get; set; }
        public int ManufacturerId { get; set; }
        public decimal Amount { get; set; }
        public int UnitId { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Product Product { get; set; }
        public virtual ICollection<SpecMaterial> SpecMaterial { get; set; }
    }
}
